name: Windows ARM64 Debug Build

on:
  workflow_dispatch:

jobs:
  windows-arm64-debug:
    name: Build Windows ARM64 Debug
    runs-on: windows-11-arm
    defaults:
      run:
        working-directory: media_kit_test
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "master"
          flutter-version: 3.44.8
      - name: Setup libmpv for Windows
        run: |
          curl -LO https://github.com/bggRGjQaUbCoE/mpv-winbuild-cmake/releases/download/20260607/mpv-dev-x86_64-20260607-git-43b14a4.7z
          cmake -E tar x mpv-dev-x86_64-20260607-git-43b14a4.7z libmpv-2.dll
        shell: cmd
      - run: flutter pub get
      - run: flutter build windows --debug --verbose
      - name: Upload PDB files
        uses: actions/upload-artifact@v7
        with:
          name: windows-arm64-debug-pdb
          path: media_kit_test/build/windows/arm64/runner/Debug/*.pdb
          if-no-files-found: error
